blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterFormView.as_view(), name="register"),
    path('posts/', views.PostListView.as_view(), name='posts'),
    path('posts/<int:pk>', views.PostDetailView.as_view(), name='post-detail'),
    path('posts/create/', views.create_post, name='create-post'),
    path('mycomments/', views.MyCommentView.as_view(), name='my-comments'),
    path('comment/create/<int:pk>', views.comment_create, name='create-comment'),
]

try1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=250)
    brief_description = models.CharField(max_length=250)
    full_description = models.CharField(max_length=500)
    image = models.URLField()
    posted = models.BooleanField(default=False)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    username = models.CharField(max_length=250)
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    posted_com = models.BooleanField(default=False)

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Comment, Post

User = get_user_model()


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class PostCreate(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'brief_description', 'full_description', 'posted']


class CommentCreate(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'posted_com']

blog/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import CommentCreate, PostCreate, RegisterForm
from .models import Comment, Post


def index(request):

    num_posts = Post.objects.count()
    num_comments = Comment.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'index.html',
        context={'num_posts': num_posts, 'num_comments': num_comments,
                 'num_visits': num_visits},
    )


class RegisterFormView(generic.FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.save()

        username = self.request.POST['username']
        password = self.request.POST['password1']

        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class PostListView(generic.ListView):
    model = Post
    paginate_by = 20
    template_name = 'post_list.html'


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'


def create_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PostCreate(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                brief_description = form.cleaned_data['brief_description']
                full_description = form.cleaned_data['full_description']
                posted = form.cleaned_data['posted']
                author = request.user
                post = Post.objects.create(title=title, brief_description=brief_description,
                                           full_description=full_description,
                                           posted=posted, author=author)
                post.save()
        else:
            form = PostCreate()
        return render(request, 'create_post.html', {'form': form})
    return HttpResponseRedirect('')


class MyCommentView(LoginRequiredMixin, generic.ListView):

    model = Comment
    template_name = 'my_comments.html'
    paginate_by = 10

    def get_queryset(self):
        return Comment.objects.filter(username=self.request.user).filter(posted_com=True)


def comment_create(request,):
    if request.method == 'POST':
        form = CommentCreate(request.POST)
        username = request.user
        if form.is_valid():
            text = form.cleaned_data['text']
            Comment.objects.create(username=username, text=text)
            return HttpResponseRedirect(reverse_lazy(''))
    else:
        form = CommentCreate()
    return render(request, 'create_comment.html', {'form': form, })

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>


<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e6e6fa;">

  <div class="container-fluid">

    <a class="navbar-brand" href="{% url 'index' %}">Home page</a>

    <div class="collapse navbar-collapse" id="navbarScroll">

      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts' %}">All posts</a>
        </li>

{#        <li class="nav-item">#}
{#          <a class="nav-link" href="{% url 'comments' %}">All comments</a>#}
{#        </li>#}
{##}
{#        <li class="nav-item">#}
{#             <a class="nav-link js-contact" href="{% url 'contact' %}">Contact Us</a>#}
{#        </li>#}
{##}
{#        {% if perms.catalog.can_mark_returned %}#}
{##}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="{% url 'all-borrowed' %}">All borrowed</a>#}
{#            </li>#}
{##}
{#        {% endif %}#}
{##}
        {% if user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'my-comments' %}">My Comments</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'create-post' %}">Create post</a>
            </li>

            <li class="nav-item">
                <a class="btn btn-outline-dark" href="{% url 'logout' %}">Logout</a>
            </li>

        {% else %}

            <li class="nav-item">
                <a class="btn btn-outline-dark" href="{% url 'register' %}">Register</a>
            </li>

            <li class="nav-item">
                <a class="btn btn-outline-dark" href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-1">
        {% block sidebar %}
        <ul class="sidebar-nav">

            {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
            {% endif %}

            {% if user.is_staff %}
                <li>Status: Staff</li>
            {% endif %}
        </ul>
      <hr />
       {% endblock %}
       </div>


<div class="col-sm-10 ">
    {% block content %}{% endblock %}

    {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
                <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
              {% if page_obj.has_next %}
                 <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
                </span>
            </div>
        {% endif %}
{% endblock %}

</body>
</html>

blog/templates/create_comment.html
{% extends 'base_generic.html' %}

{% block content %}
    <h3>Create comment:</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>


{% endblock %}

blog/templates/create_post.html
{% extends 'base_generic.html' %}
{% block content %}

    <h3>Create post:</h3>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>

{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Hillel Blog</h1>

  <p>Welcome to <em>Home page</em>.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Posts:</strong> {{ num_posts }}</li>
    <li><strong>Comments:</strong> {{ num_comments }}</li>
  </ul>

    <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}

blog/templates/my_comments.html
{% extends 'base_generic.html' %}

{% block content %}
    <h3>Your Comments:</h3>

    {% if comment_list %}
    <ul>

      {% for comment in comment_list %}
      <li>
        {{ comment.text }}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>You haven't left any comments yet.</p>
    {% endif %}


{% endblock %}

blog/templates/post_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Post title: {{ post.title }}</h1>
<style>
.raz div {
  min-height: 2em;
  margin-right: 0em;
  border: 1px solid black;
  background: #e6e6fa;
}
</style>

  <p><strong>Author:</strong> {{ post.author }}</p>
  <p><strong>Brief description:</strong> {{ post.brief_description }}</p>
  <p><strong>Image:</strong> <img src="{{ post.image }}" class="img-fluid" alt="..."></p>
  <p><strong>Full description:</strong> {{ post.full_description }}</p>
<p>
<div class="raz">
  <div><p><strong>Comments:</strong>
        {% for comment in object.comment_set.all %}
        <ul>
            <em>{{ comment.username }}</em>: {{ comment.text }}
        </ul>

        {% endfor %}
  </div>
</div>

{% endblock %}

blog/templates/post_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Post List</h1>

    {% if post_list %}
    <ul>

      {% for post in post_list %}
      <li>
        <a href="{% url 'post-detail' post.author.pk %}">{{ post.title }}</a> ({{post.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no posts in the blog.</p>
    {% endif %}
{% endblock %}}